#!/usr/bin/env bash

# Appends date + current battery capacity percentage to ~/battery.log

FILE="/home/$USER/battery.log"
CAPACITY=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep capacity)
DATE=$(date +%F)
echo $DATE $CAPACITY >> battery.log

