#!/bin/bash

ifinstalled light || exit  1

if [ "${1}" = "--level" ];
then
  BRIGHTNESS=$(light | sed 's/\..*//g');
  echo "  $BRIGHTNESS"%;
fi

[ "$1" = "--inc" ] && light -A "$2"
[ "$2" = "--dec" ] && light -U "$2"

