#!/bin/sh

# If $1 command is not available, error code and notify.
ICON="system-software-update"
command -v "$1" >/dev/null || { notify-send "📦 $1" "must be installed for this function." -i "$ICON" && exit 1 ;}
