#!/usr/bin/bash

IMAGE_VIEWER="viewnior"

# Exit if maim is not installed
ifinstalled maim || exit 1

DATE=$(date +%F_%H:%M:%S).png
FOLDER=~/Pictures/Screenshots

mkdir -p $FOLDER

FULL_PATH="$FOLDER/$DATE"

SELECTION="--selection"
FULL="--full"

FLAG=""

TITLE="Saved Screenshot"

if [ "$1" = "$SELECTION" ]; then
    FLAG="-s"
elif [ "$1" = "$FULL" ]; then
    FLAG=""
else
    echo "Missing or incorrect arguments, expected '--selection' or '--full'"
    exit 1
fi

# Screenshot, copy to clipboard and save file to path
maim -o $FLAG --quality 10 | xclip -selection clipboard -t image/png; xclip -selection clipboard -t image/png -o > $FULL_PATH

# Delete image file if it's empty
[ -s $FULL_PATH ] || rm $FULL_PATH

if [ -f "$FULL_PATH" ]; then
    if [ ! $(command -v dunstify) ]; then
        # Use notify-send to send notification if dunstify is not available
        notify-send "$TITLE" "$DATE" -i $FULL_PATH
    else
        ACTION=$(dunstify --action="open,Open Image" -u low -i $FULL_PATH "$TITLE" "$DATE")

        # Open image with middle click on notification
        case "$ACTION" in
            "open")
                $IMAGE_VIEWER $FULL_PATH &
                ;;
        esac
    fi
fi

