#!/bin/sh

# Device name to search for in 'sensors' output
DEVICE_NAME="CPU"

# Temperature to send notification if it's above it
BREAKPOINT="80"

# Get temperature (float)
SEARCH="$DEVICE_NAME.*?\+\K[0-9.]+"
TEMP=$(sensors | grep -oP $SEARCH) 

# Notification settings
TITLE="$DEVICE_NAME temperature too high!"
DESCRIPTION="Temperature: $TEMP°"

# Convert temperature to int for comparison
TEMP=${TEMP%.*}

[ "$TEMP" -gt "$BREAKPOINT" ] && notify-send "$TITLE" "$DESCRIPTION" -i 'cpu'

