#!/bin/bash

pkill -f /dev/video0 || /usr/bin/mpv /dev/video0 --profile=low-latency --geometry=-15-15 --autofit=20% --no-osc --no-input-default-bindings --input-conf=/dev/null --no-config --no-cache --no-correct-pts --untimed --video-sync=audio --mute=yes --vf=hflip

